apiVersion: v1
kind: Service
metadata:
  name: {{ include "thinknyxapp.fullname" . }}-svc
  labels:
    app: {{ include "thinknyxapp.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "thinknyxapp.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}