apiVersion: v2
name: thinknyxapp
description: A Helm chart for thinknyxapp
type: application
version: latest
appVersion: latest
keywords:
  - thinknyx
home: https://github.com/{{ .Release.Service }} # optional