name: Self-Hosted runners demo
on: 
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  j1:
    name: Running on GitHub Hosted Runner
    runs-on: ubuntu-latest
    steps:
      - name: Starting job on GitHub-hosted runner
        run: echo "This job runs on GitHub-hosted Ubuntu runner"

      - name: Display system information
        run: |
          echo "Hostname: $(hostname)"
          echo "OS Version:"
          lsb_release -a || cat /etc/os-release
          echo "Runner Name: ${{ runner.name }}"
          echo "Runner OS: ${{ runner.os }}"

      - name: Simulating work
        run: sleep 120

      - name: Finishing job
        run: echo "Job One completed successfully!"
  j2:
    name: Running on Self-Hosted Runner with single label
    runs-on: self-hosted
    steps:
      - name: Starting job on GitHub-hosted runner
        run: echo "This job runs on self-hosted runner"

      - name: Display system information
        run: |
          echo "Hostname: $(hostname)"
          echo "OS Version:"
          lsb_release -a || cat /etc/os-release
          echo "Runner Name: ${{ runner.name }}"
          echo "Runner OS: ${{ runner.os }}"

      - name: Simulating work
        run: sleep 120

      - name: Finishing job
        run: echo "Job One completed successfully!"
  j3:
    name: Running on Self-Hosted Runner with multiple labels
    runs-on: [self-hosted, python]
    steps:
      - name: Starting job on GitHub-hosted runner for python
        run: echo "This job runs on self-hosted runner"

      - name: Display system information
        run: |
          echo "Hostname: $(hostname)"
          echo "OS Version:"
          lsb_release -a || cat /etc/os-release
          echo "Runner Name: ${{ runner.name }}"
          echo "Runner OS: ${{ runner.os }}"

      - name: Simulating work
        run: sleep 120

      - name: Finishing job
        run: echo "Job One completed successfully!"
    
